#!/bin/bash

if [ ! -z "$1" -a "$1" != " " -a ! -z "$2" -a "$2" != " " -a ! -z "$3" -a "$3" != " " ]; then
        adb shell "sqlite3 /data/data/'$1'/databases/'$2' '$3'"
else
        echo "Please supply a valid Sql query, and an app package to run against"
	echo "Command syntax:"
	echo "sqlAndroid {package name} {database name} {sql query}"
fi


